apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-injector
  namespace: secret-injector
  labels:
    app.kubernetes.io/name: secret-injector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-injector:controller
  labels:
    app.kubernetes.io/name: secret-injector
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
  # - get
  # - watch
  # - list
  # - update
  # - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-injector:controller
  labels:
    app.kubernetes.io/name: secret-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-injector:controller
subjects:
- kind: ServiceAccount
  name: secret-injector
  namespace: secret-injector
