apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: from-files
  labels:
    injector.m213f.org/webhook: "true"
  annotations:
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/source: "testdata/files"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: from-files-autoprune
  labels:
    injector.m213f.org/webhook: "true"
  annotations:
    injector.m213f.org/autoprune: "true"
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/source: "testdata/files"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: from-yaml1
  labels:
    injector.m213f.org/injection: "true"
  annotations:
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/source: "testdata/yaml/data1.yaml"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: from-yaml2
  labels:
    injector.m213f.org/webhook: "true"
  annotations:
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/source: "testdata/yaml/data2.yaml"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: from-yaml2-autoprune
  labels:
    injector.m213f.org/webhook: "true"
  annotations:
    injector.m213f.org/autoprune: "true"
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/source: "testdata/yaml/data2.yaml"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: non-targeted
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
