apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test
  labels:
    injector.m213f.org/injection: "true"
  annotations:
    injector.m213f.org/repository: "masa213f/secret-injector"
    injector.m213f.org/branch: "master"
    injector.m213f.org/source: "testdata/files"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test2
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
