apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test
  labels:
    injector.m213f.org/injection: "true"
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test2
data:
  hoge: aG9nZQ==
  piyo: cGl5bw==
  fuga: ZnVnYQ==
