apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: secret-injector
  labels:
    app.kubernetes.io/name: secret-injector
spec:
  selector:
    app.kubernetes.io/name: secret-injector
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
