apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: secret-injector
  labels:
    app.kubernetes.io/name: secret-injector
webhooks:
- name: secret-injector.m213f.org
  clientConfig:
    caBundle: $(TLSCERT)
    service:
      name: webhook
      namespace: secret-injector
      path: /secrets/mutate
  failurePolicy: Fail
  objectSelector:
    matchExpressions:
      - key: injector.m213f.org/injection
        operator: In
        values:
          - "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
