apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: secret-injector
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: webhook-certs
  namespace: secret-injector
  files:
  - ca.crt=./build/ca.pem
  - tls.crt=./build/server.pem
  - tls.key=./build/server-key.pem
